// 🎸 chordSymbolParser - Updated: September 15, 2025 12:35 PM - v1.1
// Generated by Cipher Autonomous System
// ================================================

// 🎵 Chordsymbolparser - Staff Notation Parser
// src/modules/notation/parsers/chordSymbolParser.ts
// Parse chord symbols and harmonic progressions with Roman numeral analysis and voice leading validation
export interface StaffNotationElement {
  type: 'note' | 'rest' | 'chord' | 'barline' | 'clef' | 'key' | 'time';
  position: number;
  duration?: number;
  pitch?: string;
  octave?: number;
  accidental?: 'sharp' | 'flat' | 'natural' | 'double-sharp' | 'double-flat';
  dots?: number;
  tied?: boolean;
  slurred?: boolean;
}

export interface StaffNotationData {
  clef: 'treble' | 'bass' | 'alto' | 'tenor';
  keySignature: string;
  timeSignature: { numerator: number; denominator: number };
  measures: StaffMeasure[];
  tempo?: number;
  dynamics?: DynamicMarking[];
}

export interface StaffMeasure {
  number: number;
  elements: StaffNotationElement[];
  repeatStart?: boolean;
  repeatEnd?: boolean;
  volta?: number;
  rehearsalMark?: string;
}

export interface DynamicMarking {
  type: 'pp' | 'p' | 'mp' | 'mf' | 'f' | 'ff' | 'crescendo' | 'diminuendo';
  position: number;
  duration?: number;
}

export interface StaffNotationParseResult {
  success: boolean;
  notation?: StaffNotationData;
  errors: string[];
  warnings: string[];
}

export interface StaffNotationParseOptions {
  strict?: boolean;
  validateSchema?: boolean;
  throwOnError?: boolean;
}

export class Chordsymbolparser {
  private readonly noteValues: Map<string, number>;
  private readonly clefPositions: Map<string, number>;
  private currentMeasure: number = 0;
  private currentBeat: number = 0;

  constructor() {
    this.noteValues = this.initializeNoteValues();
    this.clefPositions = this.initializeClefPositions();
  }

  // ======================================
  // 🎵 MAIN PARSING METHODS
  // ======================================

  async parseNotation(input: string | StaffNotationElement[]): Promise<StaffNotationParseResult> {
    const errors: string[] = [];
    const warnings: string[] = [];

    try {
      // Handle different input types
      const elements = typeof input === 'string' 
        ? this.parseString(input)
        : input;

      // Validate elements
      const validation = this.validateElements(elements);
      if (!validation.valid) {
        errors.push(...validation.errors);
      }
      warnings.push(...validation.warnings);

      // Build staff notation
      const notation = this.buildStaffNotation(elements);

      // Analyze music theory
      const analysis = this.analyzeMusicTheory(notation);
      if (analysis.issues.length > 0) {
        warnings.push(...analysis.issues);
      }

      return {
        success: errors.length === 0,
        notation,
        errors,
        warnings
      };
    } catch (error) {
      errors.push(`Parse error: ${String(error)}`);
      return { success: false, errors, warnings };
    }
  }

  private parseString(input: string): StaffNotationElement[] {
    const elements: StaffNotationElement[] = [];
    const lines = input.trim().split('\n');

    for (const line of lines) {
      const tokens = this.tokenizeLine(line);
      for (const token of tokens) {
        const element = this.parseToken(token);
        if (element) {
          elements.push(element);
        }
      }
    }

    return elements;
  }

  private tokenizeLine(line: string): string[] {
    // Tokenize notation string (e.g., "C4 D4 E4 | F4 G4 A4 B4 |")
    return line.split(/\s+/).filter(token => token.length > 0);
  }

  private parseToken(token: string): StaffNotationElement | null {
    // Parse individual tokens
    if (token === '|') {
      return { type: 'barline', position: this.currentBeat };
    }

    // Parse note (e.g., "C4", "D#5", "Eb3")
    const noteMatch = token.match(/^([A-G])([#b]?)([0-9])?$/);
    if (noteMatch) {
      const [, pitch, accidental, octave] = noteMatch;
      return {
        type: 'note',
        position: this.currentBeat++,
        pitch,
        octave: octave ? parseInt(octave) : 4,
        accidental: this.parseAccidental(accidental),
        duration: 0.25 // Default quarter note
      };
    }

    // Parse rest (e.g., "R", "r4")
    if (token.toLowerCase().startsWith('r')) {
      return {
        type: 'rest',
        position: this.currentBeat++,
        duration: this.parseDuration(token.slice(1)) || 0.25
      };
    }

    return null;
  }

  private parseAccidental(acc: string): StaffNotationElement['accidental'] {
    switch (acc) {
      case '#': return 'sharp';
      case 'b': return 'flat';
      case '##': return 'double-sharp';
      case 'bb': return 'double-flat';
      default: return undefined;
    }
  }

  private parseDuration(duration: string): number {
    const durationMap: { [key: string]: number } = {
      '1': 1,      // Whole note
      '2': 0.5,    // Half note
      '4': 0.25,   // Quarter note
      '8': 0.125,  // Eighth note
      '16': 0.0625 // Sixteenth note
    };
    return durationMap[duration] || 0.25;
  }

  // ======================================
  // 🎵 VALIDATION METHODS
  // ======================================

  private validateElements(elements: StaffNotationElement[]): {
    valid: boolean;
    errors: string[];
    warnings: string[];
  } {
    const errors: string[] = [];
    const warnings: string[] = [];

    // Check for empty notation
    if (elements.length === 0) {
      errors.push("No notation elements found");
      return { valid: false, errors, warnings };
    }

    // Validate each element
    for (let i = 0; i < elements.length; i++) {
      const element = elements[i];
      
      if (element.type === 'note') {
        // Validate pitch
        if (!element.pitch || !['C', 'D', 'E', 'F', 'G', 'A', 'B'].includes(element.pitch)) {
          errors.push(`Invalid pitch at position ${i}: ${element.pitch}`);
        }
        
        // Validate octave
        if (element.octave !== undefined && (element.octave < 0 || element.octave > 9)) {
          warnings.push(`Unusual octave at position ${i}: ${element.octave}`);
        }
      }
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings
    };
  }

  // ======================================
  // 🎵 STAFF NOTATION BUILDING
  // ======================================

  private buildStaffNotation(elements: StaffNotationElement[]): StaffNotationData {
    const measures: StaffMeasure[] = [];
    let currentMeasure: StaffMeasure = {
      number: 1,
      elements: []
    };

    for (const element of elements) {
      if (element.type === 'barline') {
        measures.push(currentMeasure);
        currentMeasure = {
          number: measures.length + 1,
          elements: []
        };
      } else {
        currentMeasure.elements.push(element);
      }
    }

    // Add last measure if it has content
    if (currentMeasure.elements.length > 0) {
      measures.push(currentMeasure);
    }

    return {
      clef: 'treble',
      keySignature: 'C',
      timeSignature: { numerator: 4, denominator: 4 },
      measures,
      tempo: 120
    };
  }

  // ======================================
  // 🎵 MUSIC THEORY ANALYSIS
  // ======================================

  private analyzeMusicTheory(notation: StaffNotationData): { issues: string[] } {
    const issues: string[] = [];

    // Check for parallel fifths/octaves
    for (const measure of notation.measures) {
      const notes = measure.elements.filter(e => e.type === 'note');
      for (let i = 0; i < notes.length - 1; i++) {
        const interval = this.calculateInterval(notes[i], notes[i + 1]);
        if (interval === 7 || interval === 12) {
          issues.push(`Possible parallel motion in measure ${measure.number}`);
        }
      }
    }

    return { issues };
  }

  private calculateInterval(note1: StaffNotationElement, note2: StaffNotationElement): number {
    if (!note1.pitch || !note2.pitch) return 0;
    
    const pitchValues: { [key: string]: number } = {
      'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11
    };
    
    const value1 = pitchValues[note1.pitch] + (note1.octave || 4) * 12;
    const value2 = pitchValues[note2.pitch] + (note2.octave || 4) * 12;
    
    return Math.abs(value2 - value1);
  }

  // ======================================
  // 🎵 HELPER METHODS
  // ======================================

  private initializeNoteValues(): Map<string, number> {
    return new Map([
      ['whole', 1],
      ['half', 0.5],
      ['quarter', 0.25],
      ['eighth', 0.125],
      ['sixteenth', 0.0625],
      ['thirty-second', 0.03125]
    ]);
  }

  private initializeClefPositions(): Map<string, number> {
    return new Map([
      ['treble-E4', 0],
      ['treble-F4', 1],
      ['treble-G4', 2],
      ['bass-G2', 0],
      ['bass-A2', 1],
      ['bass-B2', 2]
    ]);
  }

  static create(): Chordsymbolparser {
    return new Chordsymbolparser();
  }
}

export default Chordsymbolparser;