// 🎸 validationEngine - Created: September 13, 2025 10:11 PM - v1.0
// Generated by Cipher Autonomous System
// ================================================

// 🎵 validationEngineAudio - 
// Generated by Cipher Audio Architecture Generator - Basic Audio Architecture

export interface validationEngineAudioConfig {
  sampleRate?: number;
  volume?: number;
  autoplay?: boolean;
}

export interface validationEngineAudioState {
  isPlaying: boolean;
  volume: number;
  currentTime: number;
  isInitialized: boolean;
}

export class validationEngineAudio {
  private audioContext: AudioContext | null = null;
  private config: validationEngineAudioConfig;
  private state: validationEngineAudioState;
  private gainNode: GainNode | null = null;
  private eventListeners: Map<string, Function[]> = new Map();

  constructor(config: validationEngineAudioConfig = {}) {
    this.config = {
      sampleRate: 44100,
      volume: 1.0,
      autoplay: false,
      ...config
    };

    this.state = {
      isPlaying: false,
      volume: this.config.volume || 1.0,
      currentTime: 0,
      isInitialized: false
    };

    console.log(`🎵 ${className} created`);
  }

  async initialize(): Promise<void> {
    try {
      this.audioContext = new (window.AudioContext || (window as any).webkitAudioContext)({
        sampleRate: this.config.sampleRate
      });

      this.gainNode = this.audioContext.createGain();
      this.gainNode.gain.setValueAtTime(this.state.volume, this.audioContext.currentTime);
      this.gainNode.connect(this.audioContext.destination);

      this.state.isInitialized = true;
      this.emit('initialized', { audio: this });
      
      if (this.config.autoplay) {
        this.play();
      }
      
      console.log(`🎵 ${className} initialized`);
    } catch (error) {
      console.error(`❌ Failed to initialize ${className}:`, error);
      throw error;
    }
  }

  play(): void {
    if (!this.state.isInitialized) {
      console.warn('Audio not initialized');
      return;
    }

    this.state.isPlaying = true;
    this.emit('play', { audio: this });
    console.log(`▶️ ${className} playing`);
  }

  pause(): void {
    this.state.isPlaying = false;
    this.emit('pause', { audio: this });
    console.log(`⏸️ ${className} paused`);
  }

  stop(): void {
    this.state.isPlaying = false;
    this.state.currentTime = 0;
    this.emit('stop', { audio: this });
    console.log(`⏹️ ${className} stopped`);
  }

  setVolume(volume: number): void {
    const clampedVolume = Math.max(0, Math.min(1, volume));
    this.state.volume = clampedVolume;
    
    if (this.gainNode && this.audioContext) {
      this.gainNode.gain.setValueAtTime(clampedVolume, this.audioContext.currentTime);
    }
    
    this.emit('volumeChanged', { volume: clampedVolume, audio: this });
  }

  getState(): validationEngineAudioState {
    return { ...this.state };
  }

  getCurrentTime(): number {
    return this.audioContext?.currentTime || 0;
  }

  // Event system
  on(event: string, callback: Function): void {
    if (!this.eventListeners.has(event)) {
      this.eventListeners.set(event, []);
    }
    this.eventListeners.get(event)!.push(callback);
  }

  off(event: string, callback: Function): void {
    const callbacks = this.eventListeners.get(event);
    if (callbacks) {
      const index = callbacks.indexOf(callback);
      if (index > -1) {
        callbacks.splice(index, 1);
      }
    }
  }

  private emit(event: string, data: any): void {
    const callbacks = this.eventListeners.get(event);
    if (callbacks) {
      callbacks.forEach(callback => callback(data));
    }
  }

  dispose(): void {
    if (this.audioContext) {
      this.audioContext.close();
      this.audioContext = null;
    }
    
    this.eventListeners.clear();
    this.state.isInitialized = false;
    this.emit('disposed', { audio: this });
    console.log(`🗑️ ${className} disposed`);
  }
}

export default validationEngineAudio;