// 🎸 Guitar Tabs Data - Sample tablature data
// Generated by Cipher Maestro Builder

export interface GuitarTab {
  id: string;
  title: string;
  artist: string;
  tuning: string[];
  bpm: number;
  timeSignature: string;
  tabs: TabMeasure[];
}

export interface TabMeasure {
  strings: string[]; // 6 strings, high E to low E
  timing: number[];  // Beat timing for each note
}

export const sampleTabs: GuitarTab[] = [
  {
    id: 'wonderwall-intro',
    title: 'Wonderwall (Intro)',
    artist: 'Oasis',
    tuning: ['E', 'B', 'G', 'D', 'A', 'E'],
    bpm: 87,
    timeSignature: '4/4',
    tabs: [
      {
        strings: ['3-2-0---', '3-3-3---', '0-0-0---', '0-0-0---', '2-2-2---', '3-3-3---'],
        timing: [1, 1.5, 2, 2.5, 3, 3.5]
      }
    ]
  }
];

export const guitarTabsData = {
  tabs: sampleTabs,
  getTabs: () => sampleTabs,
  getTabById: (id: string) => sampleTabs.find(tab => tab.id === id),
  addTab: (tab: GuitarTab) => sampleTabs.push(tab)
};

export default guitarTabsData;